import type { Metadata } from "next";
import { Alexandria, Lora, Raleway } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import FloatingCircle from "@/components/FloatingCircle";
import Footer from "@/components/ContactCard";

const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alexandria.variable} ${raleway.variable} ${lora.variable} relative antialiased bg-background text-foreground`}
      >
        <NavBar />
        <main className="px-10 max-w-[2000px] mx-auto">{children}</main>
        <div className="noise" />
        <FloatingCircle />
      </body>
    </html>
  );
}
